apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
  labels:
    app: grafana
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: gp2 # AWS EBS gp2 storage class for EKS
  resources:
    requests:
      storage: 10Gi # 10GB for Grafana dashboards and data
